/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z5v5c37wj3V
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { AvatarImage, Avatar } from "@/components/ui/avatar"
import { ResponsiveLine } from "@nivo/line"
import { CardContent, Card } from "@/components/ui/card"
import { ResponsiveBar } from "@nivo/bar"

export function InvDashboard() {
  return (
    <div className="bg-[#f8f9fd] p-8">
      <div className="mx-auto max-w-7xl rounded-3xl bg-white p-8 shadow-lg">
        <div className="flex justify-between">
          <div className="flex w-1/4 flex-col space-y-6">
            <div className="flex items-center space-x-4">
              <MenuIcon className="text-blue-600" />
              <Input className="flex-1" placeholder="Search" type="search" />
            </div>
            <div className="space-y-4">
              <Button className="w-full justify-start" variant="secondary">
                Dashboard
              </Button>
              <Button className="w-full justify-start" variant="ghost">
                Wallet
              </Button>
              <Button className="w-full justify-start" variant="ghost">
                Transaction
              </Button>
              <Button className="w-full justify-start" variant="ghost">
                Profile
              </Button>
              <Button className="w-full justify-start" variant="ghost">
                Payment
              </Button>
            </div>
          </div>
          <div className="w-3/4 space-y-8">
            <div className="flex justify-between">
              <h1 className="text-3xl font-bold">Dashboard</h1>
              <div className="flex items-center space-x-4">
                <Avatar>
                  <AvatarImage alt="Jonas Kanwald" src="/placeholder.svg?height=40&width=40" />
                </Avatar>
                <div>
                  <div className="text-lg font-semibold">Jonas Kanwald</div>
                  <div className="flex space-x-2">
                    <Button variant="ghost">Top Up</Button>
                    <Button variant="ghost">Pay</Button>
                    <Button variant="ghost">Send</Button>
                    <Button variant="ghost">Request</Button>
                  </div>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-8">
              <Card className="col-span-2 bg-[#eef2ff]">
                <CardContent>
                  <div className="grid grid-cols-2 gap-8">
                    <div>
                      <div className="text-lg font-semibold">Balance</div>
                      <div className="text-2xl font-bold">$ 53,250</div>
                      <div className="text-sm">CARD 05</div>
                      <div className="text-xs">6252 **** **** ****</div>
                      <div className="text-xs">VALID THRU 02/25</div>
                      <div className="text-xs">CARD HOLDER Jonas</div>
                    </div>
                    <div className="flex justify-end">
                      <CurvedlineChart className="w-full h-[200px]" />
                    </div>
                  </div>
                </CardContent>
              </Card>
              <div className="space-y-4">
                <Card className="bg-[#eef2ff]">
                  <CardContent>
                    <BarChart className="w-full h-[200px]" />
                  </CardContent>
                </Card>
                <Card className="bg-[#eef2ff]">
                  <CardContent>
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="text-lg font-semibold">Efficiency</div>
                        <div className="text-2xl font-bold">$ 1,700</div>
                        <div className="text-sm">+ 65 %</div>
                      </div>
                      <BarChart className="w-24 h-24" />
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-8">
              <div className="col-span-2 space-y-4">
                <div className="flex justify-between">
                  <h2 className="text-xl font-semibold">History</h2>
                  <MoreHorizontalIcon className="text-gray-400" />
                </div>
                <BarChart className="w-full h-[200px]" />
              </div>
              <div>
                <h2 className="text-xl font-semibold">Recent Transaction</h2>
                <div className="mt-4 space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Avatar>
                        <AvatarImage alt="Tom Holland" src="/placeholder.svg?height=32&width=32" />
                      </Avatar>
                      <div>Tom Holland</div>
                    </div>
                    <div className="text-green-500">+ $250</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Avatar>
                        <AvatarImage alt="Chris Jericho" src="/placeholder.svg?height=32&width=32" />
                      </Avatar>
                      <div>Chris Jericho</div>
                    </div>
                    <div className="text-red-500">- $250</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Avatar>
                        <AvatarImage alt="John Cena" src="/placeholder.svg?height=32&width=32" />
                      </Avatar>
                      <div>John Cena</div>
                    </div>
                    <div className="text-green-500">+ $250</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-3">
                      <Avatar>
                        <AvatarImage alt="Chris Evans" src="/placeholder.svg?height=32&width=32" />
                      </Avatar>
                      <div>Chris Evans</div>
                    </div>
                    <div className="text-red-500">- $250</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}


function BarChart(props) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}


function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}
