/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CNYFCEm2CmK
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Table() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[150px]">Formulation</TableHead>
          <TableHead>Ingredients</TableHead>
          <TableHead>Usage %</TableHead>
          <TableHead>Notes</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell className="font-medium">Moisture Magic</TableCell>
          <TableCell>Water, Glycerin, Hyaluronic Acid</TableCell>
          <TableCell>5%</TableCell>
          <TableCell className="text-right">Hydrating serum for dry skin</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Glow Getter</TableCell>
          <TableCell>Ascorbic Acid, Ferulic Acid, Vitamin E</TableCell>
          <TableCell>10%</TableCell>
          <TableCell className="text-right">Brightening treatment for dull complexion</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Clear Complex</TableCell>
          <TableCell>Salicylic Acid, Witch Hazel Extract</TableCell>
          <TableCell>2%</TableCell>
          <TableCell className="text-right">Acne-fighting toner for blemish-prone skin</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Youth Elixir</TableCell>
          <TableCell>Retinol, Peptide Complex</TableCell>
          <TableCell>1%</TableCell>
          <TableCell className="text-right">Anti-aging serum to reduce fine lines</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">Calm Balm</TableCell>
          <TableCell>Lavender Oil, Chamomile Extract</TableCell>
          <TableCell>3%</TableCell>
          <TableCell className="text-right">Soothing cream for sensitive skin</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  )
}
